/*
  The year picker: the header button that names the open school year, and the modal behind it
  that lists the years on this device and starts new ones.

  Why this is its own module rather than a few more lines in shell.js — install-banner.js set
  the shape, and this follows it: a shell feature owns its own file and shell.js only routes
  the data-* hooks to it (src/README.md, "named for the thing it owns"). It also keeps
  store.js free of the DOM, which is what lets the store be driven from the console and from a
  harness without a screen existing yet.

  The roster turns over every year and nothing may assume a fixed class list (CLAUDE.md), so
  starting next year is an ordinary thing a teacher does in August rather than a migration.
  Creating a year makes an EMPTY document and opens it; it never copies anything out of the
  year that was open. A roster carried forward automatically is a roster that is wrong for
  four classes out of five, and grades carried forward would be worse than wrong.

  Store errors are shown in the modal and announced, not put on the save chip. The chip says
  whether a save landed; "there is already a document for 2026-2027" is not a save.
*/

import { getDoc, listYears, openYear, createYear, announceYear } from './store.js';
import { openModal, closeModal } from './modal.js';
import { announce } from './live-region.js';

const MODAL_ID = 'yearModal';
const LABEL_ID = 'yearButtonLabel';
const LIST_ID = 'yearList';
const INPUT_ID = 'yearNewInput';
const ERROR_ID = 'yearError';

/* The store's messages are written for the teacher already — they say what happened and what
   to do next, per the style guide's voice — but they carry a `store:` prefix that is for the
   console. It comes off on the way to the screen. */
function readable(e) {
  return String(e && e.message ? e.message : e).replace(/^store:\s*/, '');
}

function showError(message) {
  const el = document.getElementById(ERROR_ID);
  if (!el) return;
  el.textContent = message || '';
  el.classList.toggle('hidden', !message);
  /* Also spoken: the message appears in a corner of a dialog that a screen-reader user has
     no reason to move to, and the alternative — a second aria-live region on the paragraph —
     would mean two live channels in one document. There is one, and it is announce(). */
  if (message) announce(message);
}

/* The header button's label. `—` while there is no open document, which is only ever true if
   boot failed; the loading screen is still up in that case and nobody sees it. */
export function refreshYearButton() {
  const el = document.getElementById(LABEL_ID);
  if (!el) return;
  const doc = getDoc();
  el.textContent = doc ? doc.year : '—';
}

/* Rows are built with createElement rather than an innerHTML template, and that is the
   convention for every list this app renders from the year document. A year label is
   generated by this file and safe either way — but the roster screen renders names a teacher
   pasted in from the SIS, and the habit that makes a name with an angle bracket in it into
   markup is the one being avoided here, before there is anything sensitive to render. */
async function renderYearList() {
  const list = document.getElementById(LIST_ID);
  if (!list) return;

  const years = await listYears();
  const doc = getDoc();
  const open = doc ? doc.year : '';
  /* Newest first. The year in progress is the one that wants to be under the teacher's thumb;
     last year is opened to look something up. */
  const ordered = years.slice().sort().reverse();

  list.textContent = '';
  if (!ordered.length) {
    /* Unreachable in practice — boot() creates a document when there are none — and rendered
       anyway, because a list that draws nothing looks like a bug rather than like an answer. */
    const empty = document.createElement('div');
    empty.className = 'empty-state';
    empty.textContent = 'No school years on this device yet.';
    list.append(empty);
    return;
  }

  ordered.forEach((year) => {
    const row = document.createElement('button');
    row.type = 'button';
    row.className = 'year-row' + (year === open ? ' current' : '');
    row.setAttribute('data-year-switch', year);
    if (year === open) row.setAttribute('aria-current', 'true');

    const name = document.createElement('span');
    name.textContent = year;
    const note = document.createElement('span');
    note.className = 'year-row-note';
    note.textContent = year === open ? 'Open now' : 'Switch';

    row.append(name, note);
    list.append(row);
  });
}

/* The list is rendered at open time rather than kept in sync, so that a save — which fires
   the store's subscribers — does not read every key out of IndexedDB to redraw a modal
   nobody is looking at. */
export async function openYearPicker(opener) {
  showError('');
  /* The panel opens either way. If IndexedDB refused to list the years, an inert button is a
     worse answer than a dialog saying why — and the teacher can still read which year she is
     in from the header. */
  try {
    await renderYearList();
  } catch (e) {
    showError(readable(e));
  }
  openModal(MODAL_ID, opener);
}

export async function switchYear(year) {
  try {
    await openYear(year);
  } catch (e) {
    /* Kept open, with the reason on screen. The commonest cause is the store refusing to
       leave a document whose last change would not write — closing the modal there would
       look exactly like a switch that worked. */
    showError(readable(e));
    return;
  }
  refreshYearButton();
  announceYear('Opened');
  closeModal(MODAL_ID);
}

export async function createYearFromForm() {
  const input = document.getElementById(INPUT_ID);
  if (!input) return;
  try {
    await createYear(input.value);
  } catch (e) {
    showError(readable(e));
    /* Focus back to the field: the two likely errors — a year that is not a year, and a year
       that already exists — are both fixed by editing what was typed. */
    input.focus();
    return;
  }
  input.value = '';
  refreshYearButton();
  announceYear('Created and opened');
  closeModal(MODAL_ID);
}
